### ISSUE TITLE
Enable/disable Clerk on channel

### ISSUE THREAD

**Issue by lruozzi9** [webgriffe/SyliusClerkPlugin#3]
Let's suppose this scenario:
- You have two channels, one with Clerk enabled and another without Clerk.
- The two channels use the same theme.

If you add the snippet `{{ render(url('webgriffe_sylius_clerk_tracking_code')) }}` in the layout.html.twig it will work in the channel with Clerk enabled but it will fail in the one without Clerk unless you use some fake public API key, but this could not be a solution.

There should be something saying that for the channel the scripts should not be invoked.

**Comment by lruozzi9** [comment]
@webgriffe/wg-devs any suggestions?

**Comment by mmenozzi** [comment]
The configuration is already channel-specific, see [here](https://github.com/webgriffe/SyliusClerkPlugin#configuration).

So if there's no configuration for a given channel I think that `{{ render(url('webgriffe_sylius_clerk_tracking_code')) }}` should not output anything for that channel.

**Comment by lruozzi9** [comment]
The `{{ render(url('webgriffe_sylius_clerk_tracking_code'))` will call the [PublicApiKeyProvider::providePublicApiKeyForChannel()](https://github.com/webgriffe/SyliusClerkPlugin/blob/7ee8cb42299bb1f8c76159fda40ea82534f542b2/src/Service/PublicApiKeyProvider.php#L23) with the current channel. If the method fails to find the channel code between the configured channels (if you want to have one channel without Clerk you will simply avoid adding its configuration) it will throw an Exception.
